line_length: 
  ignores_comments: true

type_name:
  max_length: 50

included:
  - Application
  - Domain
  - UIComponents
  - Network
  - Storage
excluded:
  - Application/Generated
  - UIComponents/Generated
