name: SwiftUI-MVVM
default: &iOSDeploymentTarget 16.0

configs:
  Debug (PROD): debug
  Debug (STAGING): debug
  Release (PROD): release
  Release (STAGING): release

packages:
  swift-collections:
    github: apple/swift-collections
    majorVersion: 1.0.6

  Swinject:
    github: Swinject/Swinject
    majorVersion: 2.8.0

targets:
  ########################
  ### Main Application ###
  ########################
  SwiftUI-MVVM:
    type: application
    platform: iOS
    deploymentTarget: *iOSDeploymentTarget

    configFiles:
      Debug (PROD): Application/Configuration/PROD.xcconfig
      Release (PROD): Application/Configuration/PROD.xcconfig
      Debug (STAGING): Application/Configuration/STAGING.xcconfig
      Release (STAGING): Application/Configuration/STAGING.xcconfig

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dinocata.swiftui-mvvm
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        DEVELOPMENT_TEAM: "ABCDEF123"
        INFOPLIST_FILE: Application/Info.plist
        CODE_SIGN_ENTITLEMENTS: Application/swiftui_mvvm.entitlements
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/**"
        USER_HEADER_SEARCH_PATHS: "$(SRCROOT)/**"

      configs:
        Debug (PROD):
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG PROD"
        Release (PROD):
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "RELEASE PROD"
        Debug (STAGING):
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG STAGING"
        Release (STAGING):
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "RELEASE STAGING"

    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1

    scheme:
      gatherCoverageData: true
      configVariants:
        - PROD
        - STAGING

    sources:
      - Application

    preBuildScripts:
      - name: SwiftLint
        script: scripts/swiftlint.sh
        basedOnDependencyAnalysis: false

      - name: Sourcery
        script: scripts/sourcery.sh
        basedOnDependencyAnalysis: false

      - name: SwiftGen
        script: scripts/swiftgen.sh
        basedOnDependencyAnalysis: false

    # Uncomment if Firebase is included
    #postBuildScripts:
    #  - name: Crashlytics
    #    script: "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
    #    basedOnDependencyAnalysis: false
    #    inputFiles:
    #      - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
    #      - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

    dependencies:
      - target: Domain
      - target: UIComponentsModule
      - target: NetworkModule
      - target: StorageModule

      - package: Swinject
        product: Swinject

    buildPhase:
      copyFiles:
        destination: executables

  ###############################
  ### Domain Framework ###
  ###############################
  Domain:
    type: framework
    platform: iOS
    deploymentTarget: *iOSDeploymentTarget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dinocata.swiftui-mvvm.domain
      INFOPLIST_FILE: Domain/Info.plist
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      APPLICATION_EXTENSION_API_ONLY: true
      
    sources:
      - Domain

    dependencies:
      - package: swift-collections
        product: OrderedCollections

    scheme:
      gatherCoverageData: true

  ###############################
  ### UI Components Framework ###
  ###############################
  UIComponentsModule:
    type: framework
    platform: iOS
    deploymentTarget: *iOSDeploymentTarget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dinocata.swiftui-mvvm.UIComponents
      INFOPLIST_FILE: UIComponents/Info.plist
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      APPLICATION_EXTENSION_API_ONLY: true

    sources:
      - UIComponents

    dependencies:
      - target: Domain

    scheme:
      gatherCoverageData: true

  ###############################
  ### Network Framework ###
  ###############################
  NetworkModule:
    type: framework
    platform: iOS
    deploymentTarget: *iOSDeploymentTarget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dinocata.swiftui-mvvm.network
      INFOPLIST_FILE: Network/Info.plist
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      APPLICATION_EXTENSION_API_ONLY: true
      
    sources:
      - Network

    dependencies:
      - target: Domain

    scheme:
      gatherCoverageData: true

  ###############################
  ### Storage Framework ###
  ###############################
  StorageModule:
    type: framework
    platform: iOS
    deploymentTarget: *iOSDeploymentTarget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dinocata.swiftui-mvvm.storage
      INFOPLIST_FILE: Storage/Info.plist
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      APPLICATION_EXTENSION_API_ONLY: true
      
    sources:
      - Storage

    dependencies:
      - target: Domain

    scheme:
      gatherCoverageData: true